name: Continuous Delivery

on:
    push:
        tags: ['v*']

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Clone
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "9.0"

            - name: Configure Visual Studio
              uses: microsoft/setup-msbuild@v2

            - name: Update Versions
              id: update_version
              run: |
                $ref = "${{ github.ref }}"
                if ($ref.StartsWith("refs/tags/")) {
                  $ref = $ref.Replace("refs/tags/", "")
                }

                echo "version_no_v=$($ref.Substring(1))" >> $env:GITHUB_OUTPUT

                $regex = [regex]'^v(\d+(?:\.\d+){0,2})(-.+)?$'
                $match = $regex.Match($ref)
                if (-not $match.Success) {
                  Write-Error 'Malformed version number!'
                  exit 1
                }

                $version = $match.Groups[1].Value
                $suffix = $match.Groups[2].Value

                echo "version=$version" >> $env:GITHUB_OUTPUT

                if ($version.Split('.').Length -lt 2) {
                  $version = $version + ".0"
                }

                $json = Get-Content .\version.json | ConvertFrom-Json
                $json.version = $version + $suffix
                $json | ConvertTo-Json | Set-Content .\version.json

                if ($version.Split('.').Length -lt 3) {
                  $version = $version + ".0"
                }

                [xml]$manifest = Get-Content '.\src\MSIExtract.AppxPackage\Package.appxmanifest'
                $manifest.Package.Identity.Version = "$($version).0"
                $manifest.Save('.\src\MSIExtract.AppxPackage\Package.appxmanifest')

            - name: Nerdbank.GitVersioning
              uses: dotnet/nbgv@master
              id: nbgv
              with:
                  setAllVars: true

            - name: Build
              working-directory: ./src/MSIExtract
              run: |
                ..\..\tools\make-certificate.ps1 -OutputPath .\msix\cert.pfx

                dotnet publish -c Release `
                  /p:Platform=ARM64 /p:GenerateAppxPackageOnBuild=true /p:PublicRelease=true

            - name: Prepare Assets for Upload
              working-directory: ./bin/AppxPackages
              run: |
                $uploads = (dir *.msixupload)
                if ($uploads.Length -ne 0) {
                  mv $uploads[0].FullName MSIViewer_${{ steps.update_version.outputs.version }}.msixupload -Verbose
                } else {
                  Write-Error "Could not find any msixupload files"
                  exit 1
                }

                $bundles = (dir *_Test | dir -Include *.msixbundle)
                if ($bundles.Length -ne 0) {
                  mv $bundles[0].FullName MSIViewer_${{ steps.update_version.outputs.version }}_Sideload.msixbundle -Verbose
                } else {
                  Write-Error "Could not find any msixbundle files"
                  exit 1
                }

            - name: Generate SBOM
              uses: anchore/sbom-action@v0
              with:
                path: bin/MSIExtract/ARM64/Release
                output-file: bin/MSIExtract.spdx.json

            - name: Upload Release Assets
              # This exact commit of this fork is used because it fixes a bug that would
              # cause the workflow to fail if a draft of the release already exists (which
              # it always will because we use release-drafter).
              uses: stephenway/action-gh-release@ef35f3531735d05ee289420f24b6aa256c112082
              with:
                draft: true
                name: 'MSI Viewer ${{ steps.update_version.outputs.version_no_v }}'
                tag_name: ${{ github.ref_name }}
                files: |
                  bin/MSIExtract.spdx.json
                  bin/AppxPackages/MSIViewer_${{ steps.update_version.outputs.version }}.msixupload
                  bin/AppxPackages/MSIViewer_${{ steps.update_version.outputs.version }}_Sideload.msixbundle

            - name: Attest Store Assets
              uses: actions/attest-sbom@v3
              with:
                subject-path: bin/AppxPackages/MSIViewer_${{ steps.update_version.outputs.version }}.msixupload
                sbom-path: bin/MSIExtract.spdx.json

            - name: Attest Sideload Assets
              uses: actions/attest-sbom@v3
              with:
                subject-path: bin/AppxPackages/MSIViewer_${{ steps.update_version.outputs.version }}_Sideload.msixbundle
                sbom-path: bin/MSIExtract.spdx.json
