name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7.0.0
      name: Clone
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v5.4.0
      name: Install .NET Core
      with:
        dotnet-version: "9.0"
    - name: Restore
      working-directory: ./src
      run: |
        dotnet restore
    - name: Build
      working-directory: ./src/MSIExtract
      run: |
        dotnet build -c Release
